# Generated by Django 3.0.7 on 2020-10-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('Items', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantCode', models.CharField(max_length=100)),
                ('RestaurantName', models.CharField(max_length=100)),
                ('Product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='EasyOrder.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='EasyOrder.Restaurant'),
        ),
    ]
