# Generated by Django 3.0.7 on 2020-10-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyOrder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Items',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Price',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('Items', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EasyOrder.Menu')),
            ],
        ),
    ]
