# Generated by Django 3.0.7 on 2020-10-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyOrder', '0003_auto_20201025_0416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
