# Generated by Django 3.0.7 on 2020-10-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UBHacking2020.EasyOrder.Templates.EasyOrder', '0005_auto_20201024_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Menu',
        ),
        migrations.AddField(
            model_name='product',
            name='Restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='UBHacking2020.EasyOrder.Templates.EasyOrder.Restaurant'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
